version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      APP_ENV: local
    working_dir: /var/www
    volumes:
      - ./App:/var/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # Opcional: para XDebug
    networks:
      - app-network
      
  # 🆕 ADICIONAR ESTE SERVIÇO VITE
  vite:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    container_name: vite-dev
    restart: unless-stopped
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ./App:/var/www
    working_dir: /var/www
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network
    depends_on:
      - app
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-server
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./App:/var/www  # Corrigido para App (maiúsculo)
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-sacolinhas_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    command: >
      --bind-address=0.0.0.0
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

networks:
  app-network:
    name: app-network # Nome exato da rede
    driver: bridge

volumes:
  dbdata: # Volume para persistir os dados do MySQL
    driver: local